const FETCH_SINGLE_POKEMON = 'FETCH_SINGLE_POKEMON'
const FETCH_SINGLE_POKEMON_SUCCESS = 'FETCH_SINGLE_POKEMON_SUCCESS'
const FETCH_SINGLE_POKEMON_ERROR = 'FETCH_SINGLE_POKEMON_ERROR'
const FETCH_SINGLE_POKEMON_CLEAN_SEARCH = 'FETCH_SINGLE_POKEMON_CLEAN_SEARCH'

const SET_ALL_POKEMONS = 'SET_ALL_POKEMONS'
const SET_ALL_POKEMONS_SUCCESS = 'SET_ALL_POKEMONS_SUCCESS'

const POKEMON_DETAILS_SHOW = 'POKEMON_DETAILS_SHOW'
const POKEMON_DETAILS_HIDE = 'POKEMON_DETAILS_HIDE'

export {
    FETCH_SINGLE_POKEMON,
    FETCH_SINGLE_POKEMON_SUCCESS,
    FETCH_SINGLE_POKEMON_ERROR,
    SET_ALL_POKEMONS,
    SET_ALL_POKEMONS_SUCCESS,
    FETCH_SINGLE_POKEMON_CLEAN_SEARCH,
    POKEMON_DETAILS_SHOW,
    POKEMON_DETAILS_HIDE
}